default:
  image: openjdk:11

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

stages:
  - test
  - build
  - dist
  - publish

test-jdk-default:
  stage: test
  script: ./gradlew test
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml

test-jdk-8:
  image: openjdk:8
  stage: test
  script: ./gradlew test
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml

build-core:
  stage: test
  script: ./gradlew build
  artifacts:
    paths:
      - build/distributions/*.zip
      - build/distributions/*.tar
