default:
  image: openjdk:11

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

stages:
  - test
  - build
  - dist
  - publish

test-jdk-default:
  stage: test
  script: ./gradlew test

test-jdk-8:
  image: openjdk:8
  stage: test
  script: ./gradlew test

build-core:
  stage: test
  script: ./gradlew build
  artifacts:
    paths:
      - build/distributions
