#!/usr/bin/env bash
#
# Gridify Server
# Copyright (C) 2021 Kamax Sarl
#
# https://www.kamax.io/
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

generate() {
  if [ -z "$CONF_FILE_PATH" ]; then
    echo "Config file is not set"
    exit 1
  fi

  if [ -f "$CONF_FILE_PATH" ]; then
    if [ "$1" != "--force" ] && [ "$1" != "-f" ]; then
      echo "File already exists. Use --force to overwrite"
      exit 1
    fi
    rm "$CONF_FILE_PATH"
  fi

  echo "Generating config file $CONF_FILE_PATH"
  if [[ -n "$DATA_DIR_PATH" ]]; then
      echo "Setting Data path to $DATA_DIR_PATH"
      echo "storage:" >> "$CONF_FILE_PATH"
      echo "  data: '$DATA_DIR_PATH'" >> "$CONF_FILE_PATH"
  fi

  if [[ -n "$DATABASE_CONNECTION" ]]; then
      echo "Setting Database configuration"
      echo "  database:" >> "$CONF_FILE_PATH"
      echo "    type: '$DATABASE_TYPE'" >> "$CONF_FILE_PATH"
      echo "    connection: '$DATABASE_CONNECTION'" >> "$CONF_FILE_PATH"
      echo >> "$CONF_FILE_PATH"
  fi

  echo "Configuration done!"
}

ENTRY_COMMAND="$1"
shift # We remove the first argument

case "$ENTRY_COMMAND" in
  "generate")
    generate "$@"
    exit 0
  ;;

  "gcli")
    /app/gcli "$@"
    exit $?
  ;;

  "shell")
    /bin/bash
  ;;

  *)
    if [ ! -f "$CONF_FILE_PATH" ]; then
      generate
    fi
    /app/bin/gridifyd -c "$CONF_FILE_PATH"
  ;;
esac

exit 0
