FROM postgres:11

ENV POSTGRES_USER="gridify-server"
ENV POSTGRES_PASSWORD="gridify-server"
ENV POSTGRES_DB="gridify-server"
ENV POSTGRES_INITDB_ARGS="--encoding='UTF8' --lc-collate='C' --lc-ctype='C'"
