#!/usr/bin/env bash -e

# Add service account
useradd -r gridifyd || true

# Set permissions for data directory
chown -R gridifyd:gridifyd %DEB_DATA_DIR%

# Create symlink to gridify run script
ln -sfT /usr/lib/gridify/gridifyd /usr/bin/gridifyd

# Enable systemd service
systemctl enable gridify.service
