#!/bin/bash -e

# Add service account
useradd -r gridify || true

# Set permissions for data directory
chown -R gridify:gridify %DEB_DATA_DIR%

# Create symlink to gridify run script
ln -sfT /usr/lib/gridify/gridifyd /usr/bin/gridifyd

# Enable systemd service
systemctl enable gridify.service
